name: Issue Report
description: Report an issue with FHIR documentation.
title: "[Issue]: "
labels: ["issue", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: input
    id: heading
    attributes:
      label: Heading
      description: The heading of the section where the issue was found.
      placeholder: ex. Section 1.2
    validations:
      required: true
  - type: input
    id: type
    attributes:
      label: Type
      description: The type of issue (e.g., bug, correction, suggestion).
      placeholder: ex. Bug
    validations:
      required: true
  - type: textarea
    id: selected-text
    attributes:
      label: Selected Text
      description: The text that you have selected that contains the issue.
      placeholder: Copy and paste the selected text here.
    validations:
      required: true
  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      description: Describe the change you are proposing to fix the issue.
      placeholder: Provide a detailed explanation of the proposed change.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
